// Generated by CoffeeScript 1.10.0
var _, objprint;

objprint = require('.');

_ = require('lodash');

exports.simple = function(test) {
  var actualAr, actualstr, i, j, len, obj, options, str, testAr, teststr;
  obj = [
    {
      "First Name": 'John',
      "Last Name": 'Smith',
      alive: true,
      "How.Many.Cats.Owned": 2,
      zip: '00000',
      dob: new Date('Tue Apr 2 1946 20:41:37 GMT-0400 (EDT)')
    }, {
      "First Name": 'Buckaroo',
      "Last Name": 'Banzai',
      alive: false,
      "How.Many.Cats.Owned": 1,
      zip: '12345',
      dob: new Date('Tue Dec 25 1957 20:41:37 GMT-0400 (EDT)')
    }
  ];
  options = {
    longdateformat: true
  };
  teststr = "\n                                 How\n                                 Many\n                                 Cats\nFirst Name   Last Name   alive   Owned   zip     dob\n----------   ---------   -----   -----   -----   --------------------\nJohn         Smith       true        2   00000   04/02/1946  08:41 pm\nBuckaroo     Banzai      false       1   12345   12/25/1957  07:41 pm\n  (2 rows returned)\n";
  actualstr = objprint.format(obj, options);
  actualAr = actualstr.split('\n');
  testAr = teststr.split('\n');
  for (i = j = 0, len = actualAr.length; j < len; i = ++j) {
    str = actualAr[i];
    test.equal(_.trim(str), _.trim(actualAr[i]));
  }
  console.log(actualstr);
  return test.done();
};

exports.parseTable = function(test) {
  var ar, expectedAr, tableText;
  tableText = "# this is a comment\n# ignores blank lines, and blank table rows\n\n|------|-----------|------|\n| col1 | strHeader | col3 |\n|------|-----------|------|\n|    1 | hello     |   22 |\n|    2 | world     |    4 |\n|      |           |      |\n|------|-----------|------|";
  expectedAr = [
    {
      col1: '1',
      strHeader: 'hello',
      col3: '22'
    }, {
      col1: '2',
      strHeader: 'world',
      col3: '4'
    }
  ];
  ar = objprint.parse(tableText);
  test.deepEqual(ar, expectedAr);
  return test.done();
};
